### ISSUE TITLE
What Are We Doing?

### ISSUE THREAD

**Issue by nbarrios1337** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#1]
We have our own ideas, listed in [our google doc](https://docs.google.com/document/d/1B2QYzVmuT7RnN-ApXGTr-0NChM8o0GkUij2cwPcNr24/), and the ideas in the [course google doc](https://docs.google.com/document/d/1XJ0OtTg-VD_371JqaeHw3vPTpDcyBFDrDnGgks19dXU/edit). If there's any other ideas, we can list there here or in the doc.

Lets use this as zenhub practice and for the coming recitation

**Comment by chinmayeebandal** [comment]
Yuups

**Comment by mferrera** [comment]
👻
