### ISSUE TITLE
Displays an energy (lifeline) bar on the screen.

### ISSUE THREAD

**Issue by lisander-lopez** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#109]
After this task is done, users will able to view the amount of energy you have.

### Tasks Tests
- [x] In the Ghost screen, users should be able to see the amount of energy left
- [x] The completion of this task will allow users to see their energy bar increasing/decreasing (#108)

**Comment by chinmayeebandal** [comment]
Updated the task according to the PM tool status report.
