### ISSUE TITLE
As a player, I want to see the ghost so I can pick it. 

### ISSUE THREAD

**Issue by chinmayeebandal** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#4]
**As a** user, 
**I want** to see the ghost
**so I** can pick it

Design the 

### Acceptance Tests
- [ ] Tests should be step by step confirmations of story's meaning
- [ ] Tests can be created, modified, or ~~deleted~~
- [ ] This is an incomplete item
- [x] this is an complete item

**Comment by chinmayeebandal** [comment]
Two ghosts have been designed for testing purposes.

**Comment by nbarrios1337** [comment]
As of now, we have image assets for ghosts, but our Data Model will be the "manager" that decides which button gets which image.

I suggest we push back this story to Sprint 2, where by the end of it the Data Model will be completed.
